galaxy_info:
  author: Matt Prahl
  description: automates the installation and configuration of Postfix and Dovecot with SQL authentication
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - trusty
    - xenial
  - name: EL
    versions:
      - 7
      - 8
  galaxy_tags:
  - dovecot
  - postfix
  - mysql

dependencies: []
