ver: dev
fqdn: dev.veidly.com
pg_pass: HA8lyw2M68zr16c1Zi2q49ExrarnvZc2W7C5jH2qpHcdQXJwZYdWN/g5jkddWtVy
cass_pass: sCIqvhQmvyGYoCR96xul4nKAjH/np7KWhNRSdzdIbLCuVf66qHHrbj3MVbbWYMAG
cass_hosts: '["167.235.229.133", "162.55.161.189"]'
hmac64: xnduKQ8/Zl8IRCyWcfB/OfGo+DuI/NQ47Uggai2TSfk=
chat_hmac64: eziOBeqxBkimH2hC4D2Mnt5orCkG96g5ypOBhe2FxSg=
no_reply_smtp_password: polska-mistrzem-polski-fifa-cup-2021
google_client_id: 138467161193-f5k71q6l2kcr53sjqhc3bdv1lprvtkj1.apps.googleusercontent.com
google_oauth_client_secret: 6z84Ozx-Hn-_7leB_2zlNZpD
cass_replication: "{'class':'NetworkTopologyStrategy', 'fsn1' : 2}"
p24_crc: 3e33a1c9543d1bc3
p24_username: 202115
p24_password: 990ad1193d5384b6989e3acae1e9c788
apikey: FklF1sWHs63sPn3w64LZ90BqRRCwG9mZ
