---
- name: POSTGREY | install packages
  package:
    name: postgrey
    state: present
  notify: restart postfix

- name: POSTGREY | fix (/etc/default/postgrey)
  copy:
    src: postgrey-default
    dest: /etc/default/postgrey
  notify: restart postgrey
